### ISSUE TITLE
doesnt make any changes in game

### ISSUE THREAD

**Issue by BakedMacCheese** [rogeraabbccdd/DMT2-Tool#1]
some of the songs are not in the right speed for example beyond the future NM and  HD supposed to be slow and even changing the speed in the tool application doesnt make a change

**Comment by rogeraabbccdd** [comment]
Hi, can you check your stages file in `Resource/DiscInfo`?
If your `SP` column is `1`. it means 0.5x speed, if it's `2`, it's 1.0x speed.
